# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision "shell", inline: %Q{
      apt-get update
      apt-get -y install build-essential libssl-dev libffi-dev
      apt-get install -y python-setuptools build-essential ninja-build python-dev libffi-dev libssl-dev gcc-arm-embedded git
      apt-get -y install python-pip
      add-apt-repository ppa:git-core/ppa
      apt-get -y install git
      add-apt-repository ppa:team-gcc-arm-embedded/ppa
      add-apt-repository ppa:george-edison55/cmake-3.x
      apt-get install -y cmake=3.2.2-2~ubuntu14.04.1~ppa1
      apt-get install -y gcc-msp430 gdb-msp430 msp430-libc

      mkdir -p /home/vagrant/.kubos
      easy_install pip
      # pip install kubos-cli
      # kubos update

      # TODO: removed the lines below and replace with `kubos update`
      git clone https://github.com/kubostech/kubos.git /home/vagrant/.kubos
      cd /home/vagrant/.kubos && git fetch --all

      apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
  }
  config.vm.provider "virtualbox" do |vb|
    vb.name = "kubos"
    vb.customize ['modifyvm', :id, '--usbehci', 'on']
    vb.customize ['modifyvm', :id, '--usb', 'on']
  end
end
