# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision "shell", inline: %Q{
      apt-get -y install build-essential libssl-dev libffi-dev
      apt-get -y install python-setuptools python-dev
      apt-get -y install python-pip
      add-apt-repository ppa:git-core/ppa
      apt-get -y install git
      mkdir /home/vagrant/.kubos
      # pip install kubos-cli
      # kubos update
      git clone https://github.com/kubostech/kubos.git /home/vagrant/.kubos
      cd /home/vagrant/.kubos && git fetch --all
  }
  config.vm.provider "virtualbox" do |vb|
    vb.name = "kubos"
    vb.customize ['modifyvm', :id, '--usbehci', 'on']
    vb.customize ['modifyvm', :id, '--usb', 'on']
  end
end
