# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision "shell", inline: %Q{
      apt-get update
      apt-get -y install build-essential libssl-dev libffi-dev
      apt-get install -y python-setuptools build-essential ninja-build python-dev libffi-dev libssl-dev gcc-arm-embedded git
      apt-get -y install python-pip
      add-apt-repository ppa:git-core/ppa
      apt-get -y install git
      add-apt-repository ppa:team-gcc-arm-embedded/ppa
      add-apt-repository ppa:george-edison55/cmake-3.x
      apt-get install -y cmake=3.2.2-2~ubuntu14.04.1~ppa1
      apt-get install -y gcc-msp430 gdb-msp430 msp430-libc
      apt-get install mspdebug

      # flash tools
      apt-get install dfu-util
      apt-get install openocd

      # download libmsp430.so
      wget -P /usr/lib https://github.com/kubostech/kubos/raw/vagrant-provision/vm/lib/libmsp430.so

      pip install kubos-cli
      kubos update

      apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
  }

  config.vm.provider "virtualbox" do |vb|
    vb.customize ['modifyvm', :id, '--usbehci', 'on']
    vb.customize ['modifyvm', :id, '--usb', 'on']
  end
end
