[package]
name = "rust-generic-handler"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]

[dependencies]
juniper =  "0.9.1"
juniper_iron = "0.1.1"
iron = "0.5.1"
mount = "0.3.0"
logger = "0.3.0"

extern-lib = { path = "../extern-lib" }
