[package]
name = "kubos-hal-iobc"
version = "0.1.0"
authors = ["ryan@kubos.com"]
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
kubos-build-helper = {path = "../../kubos-build-helper"}
